sudo: true
language: node_js
node_js: '8'

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - chmod +x ci/*
  - printf "@apset:registry=https:${NPM_REGISTRY}\n${NPM_REGISTRY}:_password=${NPM_PASSWORD}\n${NPM_REGISTRY}:username=${NPM_USERNAME}\n${NPM_REGISTRY}:email=${NPM_EMAIL}\n${NPM_REGISTRY}:always-auth=true\n" > .npmrc

install:
  - yarn install

script:
  - ci/lint
  - 'if [[ "${TRAVIS_TAG}" =~ ^([0-9]+\.){0,2}(\*|[0-9]+)$ ]]; then ci/publish; fi'
